---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-postgres-pvc
  namespace: devops-tools
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: synology-nas
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-postgres
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-postgres
  template:
    metadata:
      labels:
        app: devops-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: devops
            - name: POSTGRES_USER
              value: devops
            - name: POSTGRES_PASSWORD
              value: devops123
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: devops-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: devops-postgres
  namespace: devops-tools
spec:
  selector:
    app: devops-postgres
  ports:
    - port: 5432
      targetPort: 5432
