---
apiVersion: v1
kind: Secret
metadata:
  name: devops-backend-secret
  namespace: devops-tools
type: Opaque
stringData:
  DB_HOST: devops-postgres
  DB_PORT: "5432"
  DB_NAME: devops
  DB_USERNAME: devops
  DB_PASSWORD: devops123
  HARBOR_URL: https://harbor.devops.cicd.test
  HARBOR_USERNAME: admin
  HARBOR_PASSWORD: vmffpdltm
  HARBOR_PROJECT: devops-upstream
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-packages-pvc
  namespace: devops-tools
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: synology-nas
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: backend
          image: harbor.devops.cicd.test/devops-platform/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          envFrom:
            - secretRef:
                name: devops-backend-secret
          volumeMounts:
            - name: packages
              mountPath: /data/packages
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: packages
          persistentVolumeClaim:
            claimName: devops-packages-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: devops-backend
  namespace: devops-tools
spec:
  selector:
    app: devops-backend
  ports:
    - port: 8080
      targetPort: 8080
